version: '3'

services:
    front:
        container_name: guessthegame-front
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        image: guessthegame/guessthegame-front
        ports:
            - 80:80
