version: '3'

services:
    dev:
        container_name: guessthegame-front-dev
        image: paulintrognon/guessthegame-front-dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        environment:
          - NODE_ENV=development
          - API_URL=${API_URL}
          - RECAPTCHA_KEY=${RECAPTCHA_KEY}
        ports:
            - ${DEV_PORT:-3000}:3000
            - 35729:35729
        volumes:
          - .:/usr/src/app
    prod:
        container_name: guessthegame-front
        image: paulintrognon/guessthegame-front
        build:
            context: .
            dockerfile: Dockerfile
        environment:
          - NODE_ENV=production
          - API_URL=${API_URL}
          - RECAPTCHA_KEY=${RECAPTCHA_KEY}
        ports:
          - ${PORT:-80}:3000
